blank_issues_enabled: false
contact_links:
  - name: Knex issue
    url: https://github.com/knex/knex/issues/new
    about: For bug reports in Knex itself
  - name: Support
    url: https://gitter.im/tgriesser/knex
    about: For support, see Gitter or Stack Overflow
